version: "2.4"

services:
  # Dependencies
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: hwl_storage_key
      MINIO_ROOT_PASSWORD: Ch@ngeTh!sPa33w0rd
    ports:
      - "9000:9000"
    command: server /data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - logger.level=WARN
      - "ELASTIC_PASSWORD=devpass"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - http.cors.allow-origin=http://localhost:8080
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail -u elastic:$$ELASTIC_PASSWORD localhost:9200/_cluster/health || exit 1"
        ]
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis
    ports:
      - "6379:6379"
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  default:
    name: external
